/**
 * program.ts — IDL-driven access to nexus_launchpad from the admin console.
 *
 * One casing rule, and it matters: `new Program(idl)` converts the whole IDL to
 * camelCase, so every method, account name and struct field goes through the
 * client as camelCase (`updatePlatformFeeConfig`, `registry.emergencyPause`,
 * `{ core: {} }` for enum variants). Passing snake_case keys does NOT throw —
 * anchor's layout silently encodes zeros for the fields it cannot find, which
 * produces a well-formed transaction that sets everything to 0. Build args
 * through `program.methods.*` and read accounts through `program.account.*` and
 * that trap stays shut.
 *
 * The IDL is a copy of Frontend/lib/solana/idl/nexus_launchpad.json, itself
 * generated by programs/scripts/build-deploy.sh. Keep this the only module in
 * the admin app that imports it.
 */
import { AnchorProvider, Program, type Idl } from '@coral-xyz/anchor'
import { Connection, PublicKey } from '@solana/web3.js'
import idlJson from './idl/nexus_launchpad.json'

/** A wallet that signs nothing — Program is only ever used to BUILD instructions. */
const NOOP_WALLET = {
  publicKey: PublicKey.default,
  signTransaction: async <T>(tx: T) => tx,
  signAllTransactions: async <T>(txs: T[]) => txs,
}

/**
 * An anchor Program bound to `connection`, targeting `programId` from
 * GET /api/solana/config rather than whatever address the committed IDL carries
 * (the IDL lags a redeploy; the backend never does).
 */
export function getProgram(connection: Connection, programId?: PublicKey | string): Program {
  const provider = new AnchorProvider(connection, NOOP_WALLET as never, { commitment: 'confirmed' })
  const idl: Idl = programId
    ? { ...(idlJson as Idl), address: typeof programId === 'string' ? programId : programId.toBase58() }
    : (idlJson as Idl)
  return new Program(idl, provider)
}

// ── PDAs ─────────────────────────────────────────────────────────────────────
// Seeds must match programs/programs/nexus-launchpad/src/lib.rs exactly.
// Encoded as Uint8Array rather than Buffer so nothing here depends on a Node
// global being polyfilled into the browser bundle.

const seed = (text: string) => new TextEncoder().encode(text)

export const REGISTRY_SEED = seed('registry')
export const PLATFORM_FEE_CONFIG_SEED = seed('platform_fee_config')
export const COLLECTION_SEED = seed('collection')

export function deriveRegistryPda(programId: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync([REGISTRY_SEED], programId)[0]
}

export function derivePlatformFeeConfigPda(programId: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync([PLATFORM_FEE_CONFIG_SEED], programId)[0]
}

export function deriveCollectionPda(mintSeed: PublicKey, programId: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync([COLLECTION_SEED, mintSeed.toBuffer()], programId)[0]
}

// ── Program constants mirrored from the Rust ─────────────────────────────────

/**
 * Hard cap on the flat per-NFT platform fee, in lamports (1 SOL), enforced by
 * write_platform_fee_config / update_platform_fee. Was 1500 bps under the old
 * percentage model.
 */
export const MAX_PLATFORM_FEE_LAMPORTS = 1_000_000_000
/** PlatformFeeConfig::recipients is a fixed [Pubkey; 4]. */
export const MAX_PLATFORM_FEE_RECIPIENTS = 4
/** Platform fee shares are basis points and must sum to exactly this. */
export const PLATFORM_FEE_SHARE_TOTAL_BPS = 10_000
/** initiate_upgrade bounds (non-localnet build). */
export const MIN_UPGRADE_DELAY_SECONDS = 86_400
export const MAX_UPGRADE_DELAY_SECONDS = 7 * 86_400
/** CollectionRegistry::MAX_COLLECTIONS. */
export const MAX_COLLECTIONS = 300

/** UpgradeState as stored in registry.upgradeState. */
export const UPGRADE_STATE = {
  None: 0,
  Initiated: 1,
  Completed: 2,
  Cancelled: 3,
} as const

/** Collection.status values. */
export const COLLECTION_STATUS_LABELS = [
  'Draft',
  'Preparing',
  'Ready',
  'Minting',
  'Completed',
  'Paused',
] as const

/** Collection.flags bitmask. */
export const COLLECTION_FLAGS = {
  paused: 1 << 0,
  freezeUntilSoldOut: 1 << 1,
  hasSplit: 1 << 2,
  hasPhaseSchedule: 1 << 3,
  hasRoyalties: 1 << 4,
} as const

// ── Decoded account shapes (camelCase — see the header note) ─────────────────

/** Anchor decodes u64/i64 to BN; we only ever need toString()/toNumber(). */
export interface Bnish {
  toString(radix?: number): string
  toNumber(): number
}

export interface RegistryAccount {
  authority: PublicKey
  pendingAuthority: PublicKey | null
  pendingUpgradeProgram: PublicKey
  upgradeInitiatedTime: Bnish
  upgradeCompletionTime: Bnish
  emergencyPauseTime: Bnish
  collections: PublicKey[]
  collectionCount: number
  upgradeState: number
  emergencyPause: boolean
  bump: number
}

export interface PlatformFeeConfigAccount {
  recipients: PublicKey[]
  /** Flat platform fee per NFT, lamports. Copied into each collection at creation. */
  feeLamports: Bnish
  sharesBps: number[]
  num: number
  bump: number
}

export interface CollectionAccount {
  authority: PublicKey
  mint: PublicKey
  mintAuthority: PublicKey
  creatorWallet: PublicKey
  platformWallet: PublicKey
  maxSupply: Bnish
  minted: Bnish
  price: Bnish
  startTime: Bnish
  endTime: Bnish
  freezeUntil: Bnish
  createdAt: Bnish
  /** Flat platform fee per NFT, lamports — frozen at create_collection. */
  platformFeeLamports: Bnish
  allowlistRoot: number[]
  mintLimitPerWallet: number
  metadataStandard: number
  flags: number
  status: number
  featured: boolean
  bump: number
  metadataUri: string
}

/**
 * `program.account` is typed against a generic Idl, so the named accounts are not
 * known statically. This narrows it to the three we read, in one place, instead
 * of casting at every call site.
 */
interface AccountNamespace {
  collectionRegistry: {
    fetchNullable(address: PublicKey): Promise<RegistryAccount | null>
  }
  platformFeeConfig: {
    fetchNullable(address: PublicKey): Promise<PlatformFeeConfigAccount | null>
  }
  collection: {
    fetchMultiple(addresses: PublicKey[]): Promise<(CollectionAccount | null)[]>
    fetchNullable(address: PublicKey): Promise<CollectionAccount | null>
  }
}

export function accounts(program: Program): AccountNamespace {
  return program.account as unknown as AccountNamespace
}
